### ISSUE TITLE
Make a type alias for the requester constraint

### ISSUE THREAD

**Issue by 3noch** [dfordivam/reflex-websocket-interface#4]
`Reflex.Dom.WebSocket.Monad` should probably export `IsWebSocketRequest` and `IsWebSocketResponse`. Also handy would be a constraint to easily allow users to be polymorphic on it:

```
type HasWebSocket t msg m = Requester t (IsWebSocketRequest msg) (IsWebSocketResponse msg) m
```

**Comment by 3noch** [comment]
Fixed by #5

**Comment by dfordivam** [comment]
This should have closed automatically...
anyways...

**Comment by 3noch** [comment]
@dfordivam I had the wrong issue number in the PR when you merged it.
